name: prigra_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  form_field_validator: ^1.1.0
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^1.0.0
  shared_preferences: ^2.1.1
  animated_text_kit:
  page_transition:
  animations:
  flutter_staggered_animations:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  

  assets:
    - assets/illustrations/
    - assets/icons/
    - google_fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: google_fonts/Ubuntu-Bold.ttf
          weight: 800
        - asset: google_fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: google_fonts/Ubuntu-Regular.ttf
          weight: 300